# Render Blueprint config
services:
  - type: web
    name: contractchatbot
    env: python
    buildCommand: pip install -r requirements.txt && python migrations/enable_pgvector.py
    startCommand: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 120 --bind 0.0.0.0:$PORT
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chatbotdb_q346
          property: connectionString

databases:
  - name: chatbotdb_q346
    plan: free 